"""empty message

Revision ID: 901475339e3d
Revises: c649e88298a2
Create Date: 2022-08-20 10:16:15.382711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901475339e3d'
down_revision = 'c649e88298a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), default=False))
    op.drop_column('Venue', 'looking_for_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
